# Force ROS libraries to build and link against Unreal's OpenSSL

set(UE_THIRD_PARTY_PATH "$ENV{UE_THIRD_PARTY_PATH}")

set(CMAKE_FIND_PACKAGE_PREFER_CONFIG OFF)

set(OPENSSL_FOUND TRUE)
set(OPENSSL_ROOT_DIR "${UE_THIRD_PARTY_PATH}/OpenSSL/1.1.1t")
set(OPENSSL_USE_STATIC_LIBS TRUE)
set(OPENSSL_INCLUDE_DIR "${UE_THIRD_PARTY_PATH}/OpenSSL/1.1.1t/include/Mac")
set(OPENSSL_CRYPTO_LIBRARY "${UE_THIRD_PARTY_PATH}/OpenSSL/1.1.1t/lib/Mac/libcrypto.a")
SET(OPENSSL_SSL_LIBRARY "${UE_THIRD_PARTY_PATH}/OpenSSL/1.1.1t/lib/Mac/libssl.a")
SET(OPENSSL_LIBRARIES "${UE_THIRD_PARTY_PATH}/OpenSSL/1.1.1t/lib/Mac/libssl.a ${UE_THIRD_PARTY_PATH}/OpenSSL/1.1.1t/lib/Mac/libcrypto.a")
SET(OPENSSL_VERSION "1.1.1t")

if(NOT TARGET OpenSSL::Crypto)
    add_library(OpenSSL::Crypto STATIC IMPORTED)
endif()
set_target_properties(OpenSSL::Crypto PROPERTIES
    IMPORTED_LOCATION "${OPENSSL_CRYPTO_LIBRARY}"
    IMPORTED_LINK_INTERFACE_LANGUAGES "C"
    INTERFACE_INCLUDE_DIRECTORIES "${OPENSSL_INCLUDE_DIR}")

if(NOT TARGET OpenSSL::SSL)
    add_library(OpenSSL::SSL STATIC IMPORTED)
endif()
set_target_properties(OpenSSL::SSL PROPERTIES
    IMPORTED_LOCATION "${OPENSSL_SSL_LIBRARY}"
    IMPORTED_LINK_INTERFACE_LANGUAGES "C"
    INTERFACE_INCLUDE_DIRECTORIES "${OPENSSL_INCLUDE_DIR}")
